name: CI
on: [push]
jobs:    
  build:
    runs-on: ubuntu-18.04
    container: gcc:8.4
    steps:
      - uses: actions/checkout@v1
      - name: Install package dependencies
        run: |
          apt-get update
          apt install -y gcovr lcov libboost-all-dev wget unzip zip

      - name: Install Cmake
        run: |
          cd ~
          wget https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.sh \
          -q -O /tmp/cmake-install.sh \
          && chmod u+x /tmp/cmake-install.sh \
          && mkdir /usr/bin/cmake \
          && /tmp/cmake-install.sh --skip-license --prefix=/usr/bin/cmake \
          && rm /tmp/cmake-install.sh
          export PATH="/usr/bin/cmake/bin:${PATH}"

      - name: Install gtest/gmock
        run: |
          cd ~
          wget -O googletest.zip https://github.com/google/googletest/archive/release-1.10.0.zip
          unzip googletest.zip
          mv googletest-release-1.10.0 googletest
          cd ~/googletest
          mkdir build
          cd ~/googletest/build
          cmake .. && \
          make -j4 && \
          make install && \
          ldconfig
          cd ~
          rm -r googletest googletest.zip

      - name: Build code
        run: |
          cd ~
          mkdir build
          cd ~/build
          cmake .. && \
          make -j4



      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ~/coverage