name: CI
on: [push]
jobs:    
  build:
    runs-on: ubuntu-18.04
    container: docker.pkg.github.com/sujaypillai/buildxdemo/demo:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install package dependencies
        run: |
          apt-get update
          apt install -y gcovr lcov libboost-all-dev wget unzip zip


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ~/coverage