name: CI
on: [push]
jobs:    
  build:
    runs-on: ubuntu-18.04
    container: 
      image: docker.pkg.github.com/ximenesfel/cpp_github_actions/cpp:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr_token }}
    steps:
      - uses: actions/checkout@v1

      - name: Build code
        run: |
          ls -la ~
          # cd ~
          # mkdir build
          # cd ~/build
          # cmake .. && make